name: nemascan
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - pandoc=2.12
  - plink=1.90b6.12
  - bedtools=2.29.2
  - r=3.6.0
  - r-devtools
  - r-data.table=1.12.8
  - r-DT=0.12
  - r-genetics=1.3.8.1.2
  - r-ggbeeswarm=0.6.0
  - r-ggnewscale=0.4.5
  - r-ggrepel=0.8.2
  - r-knitr=1.28
  - r-rmarkdown=2.1
  - r-plotly=4.9.2
  - r-RSpectra=0.16-0
  - r-sommer=4.0.4
  - r-coop=0.6-2
  - r-Rcpp=1.0.1
  - r-cowplot=1.0.0
  - r-valr

#  - bioconductor-ComplexHeatmap=2.4.2