name: nemascan
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - pandoc=2.12
  - plink=1.90b6.12
  - bedtools=2.29.2
  #- gcta=1.92.3
  - r=3.6.1
  - r-devtools
  - r-data.table
  - r-DT
  - r-genetics
  - r-ggbeeswarm
  - r-ggnewscale
  - r-ggrepel
  - r-knitr
  - r-rmarkdown
  - r-plotly
  - r-RSpectra
  - r-sommer
  - r-coop
  - r-Rcpp
  - r-cowplot
  - r-valr
#  - bioconductor-ComplexHeatmap=2.4.2