# Build dockerfile on change
name: Build Docker (env/ibdseq.nemascan.Dockerfile)

on:
  push:
    paths:
    - 'env/ibdseq.nemascan.Dockerfile'
    - 'env/ibdseq.nemascan.yml'
    - '.github/workflows/build_ibdseq_nemascan_docker.yml'
  pull_request:
    paths:
    - 'env/ibdseq.nemascan.Dockerfile'
    - 'env/ibdseq.nemascan.yml'
    - '.github/workflows/build_ibdseq_nemascan_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: andersenlab/ibdseq.nemascan
        tag: "${{ steps.current-time.formattedTime }}"
        username: ${{ secrets.KSE_DOCKER_USER }}
        password: ${{ secrets.KSE_DOCKER_PASS }}
        snapshot: true
        dockerfile: ibdseq.nemascan.Dockerfile
        workdir: "env"
        tags: "latest"
        cache: true
